name: walk-park
channels:
- jamespreed
- conda-forge
dependencies:
- osmnx=1.1.*
- pandana=0.6.*
- pip=21.1.*
- descartes=1.1.*
- python=3.9.*
- seaborn=0.11.*
- ipykernel=6.0.*
- matplotlib=3.4.*
- conda-minify=0.1.*
- nbconvert=6.1.*
